name: thesis
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==1.23.5
      - pandas==2.2.3
      - matplotlib==3.10.0
      - scipy==1.15.3
      - scikit-learn==1.6.1
      - tensorflow==2.10.1
      - keras==2.10.0
      - keras-tuner==1.4.8
      - joblib==1.5.3
      - dysts==0.96
      - numba
